### ISSUE TITLE
Model very slow on cpu

### ISSUE THREAD

**Issue by AndreyStille** [levindabhi/cloth-segmentation#1]
Hi, thanks for excellent clothes segmentation model.
But model is very slow when inferencing on cpu. In colab demo it takes 14s. for one inference without GPU. Even after converting model to onnx, and openvino format I reached only 2s for inference. 
Any ideas why it's so slow?

**Comment by levindabhi** [comment]
Hello, 
Yes due to the larger model size it works slow on cpu.
The model used here is [u2net](https://github.com/xuebinqin/U-2-Net). You can retrain u2net-p or have a look into this [issue](https://github.com/xuebinqin/U-2-Net/issues/165)

**Comment by AndreyStille** [comment]
> Hello, Yes due to the larger model size it works slow on cpu. The model used here is [u2net](https://github.com/xuebinqin/U-2-Net). You can retrain u2net-p or have a look into this [issue](https://github.com/xuebinqin/U-2-Net/issues/165)

Thank you very much
