### ISSUE TITLE
Getting the predictions

### ISSUE THREAD

**Issue by Lord-Psarris** [levindabhi/cloth-segmentation#8]
When I run the infer.py it segments the image but I don't get any of the detected objects or classes. and always have to refer to the image Is there a way I can get the segmented classes (e.g. upper, lower etc.) ?

**Comment by karndeepsingh** [comment]
Hi @Lord-Psarris,
Any successful approach for segmenting different classes as you mentioned in the issue?

Please help, I have similar issue.

Thanks

**Comment by Lord-Psarris** [comment]
Hello @karndeepsingh,
I made a simple script to detect the colors in the image.

The segmented image mask have a max of 4 colors (black for background, and 3 others for full body, upper body and lower body), so it simply checks the pixels to see which of the colors are detected in the image.

You might want to optimize the image or reduce its resolution first if computing time and memory are an issue. Let me know if you'd like to see my implementation

**Comment by karndeepsingh** [comment]
> Hello @karndeepsingh, I made a simple script to detect the colors in the image.
> 
> The segmented image mask have a max of 4 colors (black for background, and 3 others for full body, upper body and lower body), so it simply checks the pixels to see which of the colors are detected in the image.
> 
> You might want to optimize the image or reduce its resolution first if computing time and memory are an issue. Let me know if you'd like to see my implementation

That’s great @Lord-Psarris 
Can you share your work? I would like to understand it.

Thankyou so much

**Comment by kumar-hardik** [comment]
@karndeepsingh @Lord-Psarris 
I have similar issue, can you guys help with the script to retrive the original colors for the segmentation?

**Comment by Lord-Psarris** [comment]
@karndeepsingh , @kumar-hardik here is a[ google collab](https://colab.research.google.com/drive/1bseSsWkTxlNfv9Twy_6tWLzVWNZ8jeSq?usp=sharing) of my implementation. 
Feel free to utilize it as you see fit

**Comment by Lord-Psarris** [comment]
@kumar-hardik , @karndeepsingh you can find my complete solution here:
https://github.com/Lord-Psarris/cloth-segmentation
